apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openwork.fullname" . }}
  labels:
    {{- include "openwork.labels" . | nindent 4 }}
type: Opaque
data:
  auth-token: {{ default (randAlphaNum 32) .Values.openwork.authToken | b64enc | quote }}
