apiVersion: v1
kind: Service
metadata:
  name: {{ include "openwork.fullname" . }}-http
  labels:
    {{- include "openwork.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8787
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openwork.selectorLabels" . | nindent 4 }}
